### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by ViktoriiaHryshko** [AntonBurchak/Final-project-epam#1]
1. Home and portfolio pages don't have "Add new post" button;
2. Look at this. Be carefull with all elements, think about details. 

![image](https://user-images.githubusercontent.com/21124577/92040057-cc736c00-ed7e-11ea-82e8-abcd9673737a.png)

![image](https://user-images.githubusercontent.com/21124577/92039746-41927180-ed7e-11ea-95b2-003bef464613.png)

3. `<div />` can't be inside `<label />`;

![image](https://user-images.githubusercontent.com/21124577/92040165-06447280-ed7f-11ea-89fe-ac7df0781a92.png)

4.  Don't use  redundant values - such as 'value' in the next code:
const dateInput = Controller.form.querySelector('input[type=date]'),
```

date = new Date().getDate() < 10 ? '0' + (new Date().getDate()) : (new Date().getDate()),

year = new Date().getFullYear(),

month = new Date().getMonth() < 10 ? '0' + (new Date().getMonth() + 1) : (new Date().getMonth() + 1),

value = ${year}-${month}-${date};

dateInput.value = value;
```

Better:  
```
...

dateInput.value = ${year}-${month}-${date};
```

5.  Exista lot of  unused code
For example: 
![image](https://user-images.githubusercontent.com/21124577/92041551-1b220580-ed81-11ea-8b29-c6ee51601bc0.png)

And too entangled logic.

6. Better use BEM. For example, class "primary" better use as modificator "intro__btn btn btn--primary"  

7. Don't use superfluous tags and tags without classes.

### 
### 
 **Well done in general!**

**Comment by AntonBurchak** [comment]
- [x] Home and portfolio pages don't have "Add new post" button;

- [ ] Look at this. Be carefull with all elements, think about details.

- [ ] <div /> can't be inside <label />

- [ ] Don't use redundant values - such as 'value' 

- [ ] Exista lot of unused code

- [ ] Better use BEM.

- [ ] Don't use superfluous tags and tags without classes.

**Comment by AntonBurchak** [comment]
Thanks for your review!
New version is already upload!
